"use client";

import { useState, useEffect } from "react";
import { getInstallments } from "@/services/real-estate/installments";
import { columns, InstallmentWithRelations } from "./columns";
import { DataTable } from "@/components/datatable/data-table";

export default function InstallmentsPage() {
  const [data, setData] = useState<InstallmentWithRelations[]>([]);

  useEffect(() => {
    const fetchData = async () => {
      const installments = await getInstallments();
      setData(installments as InstallmentWithRelations[]);
    };
    fetchData();
  }, []);

  return (
    <div className="container mx-auto py-10">
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-3xl font-bold">إدارة الأقساط</h1>
        {/* Add Installment button can go here if needed, though they are generated by contracts */}
      </div>
      <DataTable
        columns={columns}
        data={data}
        filterColumn="contract.client.name"
        filterPlaceholder="فلترة باسم العميل..."
      />
    </div>
  );
}
